;;; phpinspect-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from phpinspect.el

(autoload 'phpinspect-find-class-file "phpinspect" "\
`find-file', but for FQNs of PHP classes.

When called interactively, presents the the user with a list of
available FQNs in a project.  This may require
`phpinspect-index-current-project' to have run once for the
project directory before it can be used.

(fn FQN)" t)
(register-definition-prefixes "phpinspect" '("phpinspect-"))


;;; Generated autoloads from phpinspect-autoload.el

(register-definition-prefixes "phpinspect-autoload" '("phpinspect-"))


;;; Generated autoloads from phpinspect-bmap.el

(register-definition-prefixes "phpinspect-bmap" '("phpinspect-"))


;;; Generated autoloads from phpinspect-buffer.el

(register-definition-prefixes "phpinspect-buffer" '("phpinspect-"))


;;; Generated autoloads from phpinspect-cache.el

(register-definition-prefixes "phpinspect-cache" '("phpinspect-"))


;;; Generated autoloads from phpinspect-changeset.el

(register-definition-prefixes "phpinspect-changeset" '("phpinspect-"))


;;; Generated autoloads from phpinspect-completion.el

(register-definition-prefixes "phpinspect-completion" '("phpinspect-"))


;;; Generated autoloads from phpinspect-edtrack.el

(register-definition-prefixes "phpinspect-edtrack" '("phpinspect-"))


;;; Generated autoloads from phpinspect-eldoc.el

(register-definition-prefixes "phpinspect-eldoc" '("phpinspect-"))


;;; Generated autoloads from phpinspect-fs.el

(register-definition-prefixes "phpinspect-fs" '("phpinspect-"))


;;; Generated autoloads from phpinspect-imports.el

(register-definition-prefixes "phpinspect-imports" '("phpinspect-"))


;;; Generated autoloads from phpinspect-index.el

(register-definition-prefixes "phpinspect-index" '("phpinspect-"))


;;; Generated autoloads from phpinspect-meta.el

(register-definition-prefixes "phpinspect-meta" '("phpinspect-m"))


;;; Generated autoloads from phpinspect-method-cell.el

(register-definition-prefixes "phpinspect-method-cell" '("phpi"))


;;; Generated autoloads from phpinspect-parse-context.el

(register-definition-prefixes "phpinspect-parse-context" '("phpinspect-"))


;;; Generated autoloads from phpinspect-parser.el

(register-definition-prefixes "phpinspect-parser" '("phpinspect-"))


;;; Generated autoloads from phpinspect-pipeline.el

(register-definition-prefixes "phpinspect-pipeline" '("phpinspect-"))


;;; Generated autoloads from phpinspect-project.el

(register-definition-prefixes "phpinspect-project" '("phpinspect-"))


;;; Generated autoloads from phpinspect-property-cell.el

(register-definition-prefixes "phpinspect-property-cell" '("phpi"))


;;; Generated autoloads from phpinspect-queue.el

(register-definition-prefixes "phpinspect-queue" '("phpinspect-"))


;;; Generated autoloads from phpinspect-resolve.el

(register-definition-prefixes "phpinspect-resolve" '("phpinspect-"))


;;; Generated autoloads from phpinspect-resolvecontext.el

(register-definition-prefixes "phpinspect-resolvecontext" '("phpinspect-"))


;;; Generated autoloads from phpinspect-serialize.el

(register-definition-prefixes "phpinspect-serialize" '("phpinspect--serialize-"))


;;; Generated autoloads from phpinspect-splayt.el

(register-definition-prefixes "phpinspect-splayt" '("phpinspect-"))


;;; Generated autoloads from phpinspect-suggest.el

(register-definition-prefixes "phpinspect-suggest" '("phpinspect-"))


;;; Generated autoloads from phpinspect-toc.el

(register-definition-prefixes "phpinspect-toc" '("phpinspect-"))


;;; Generated autoloads from phpinspect-token-predicates.el

(register-definition-prefixes "phpinspect-token-predicates" '("phpinspect-"))


;;; Generated autoloads from phpinspect-type.el

(register-definition-prefixes "phpinspect-type" '("phpinspect-"))


;;; Generated autoloads from phpinspect-typedef.el

(register-definition-prefixes "phpinspect-typedef" '("phpi"))


;;; Generated autoloads from phpinspect-util.el

(register-definition-prefixes "phpinspect-util" '("phpinspect-"))


;;; Generated autoloads from phpinspect-worker.el

(register-definition-prefixes "phpinspect-worker" '("phpinspect-"))

;;; End of scraped data

(provide 'phpinspect-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; phpinspect-autoloads.el ends here
